/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardOrgIdRouteRouteImport } from './routes/_authenticated/dashboard/$orgId/route'
import { Route as AuthenticatedDashboardAutogradingRouteImport } from './routes/_authenticated/dashboard/autograding'
import { Route as AuthenticatedDashboardOrganizationsRouteImport } from './routes/_authenticated/dashboard/organizations'
import { Route as AuthenticatedDashboardRostersRouteRouteImport } from './routes/_authenticated/dashboard/rosters/route'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDashboardOrgIdIndexRouteImport } from './routes/_authenticated/dashboard/$orgId/index'
import { Route as AuthenticatedDashboardOrgIdClassIdRouteImport } from './routes/_authenticated/dashboard/$orgId/$classId'
import { Route as AuthenticatedDashboardRostersIndexRouteImport } from './routes/_authenticated/dashboard/rosters/index'
import { Route as AuthenticatedDashboardRostersRosterIdRouteImport } from './routes/_authenticated/dashboard/rosters/$rosterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrgIdRouteRoute =
  AuthenticatedDashboardOrgIdRouteRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAutogradingRoute =
  AuthenticatedDashboardAutogradingRouteImport.update({
    id: '/autograding',
    path: '/autograding',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrganizationsRoute =
  AuthenticatedDashboardOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRostersRouteRoute =
  AuthenticatedDashboardRostersRouteRouteImport.update({
    id: '/rosters',
    path: '/rosters',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardOrgIdIndexRoute =
  AuthenticatedDashboardOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardOrgIdRouteRoute,
  } as any)
const AuthenticatedDashboardOrgIdClassIdRoute =
  AuthenticatedDashboardOrgIdClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => AuthenticatedDashboardOrgIdRouteRoute,
  } as any)
const AuthenticatedDashboardRostersIndexRoute =
  AuthenticatedDashboardRostersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRostersRouteRoute,
  } as any)
const AuthenticatedDashboardRostersRosterIdRoute =
  AuthenticatedDashboardRostersRosterIdRouteImport.update({
    id: '/$rosterId',
    path: '/$rosterId',
    getParentRoute: () => AuthenticatedDashboardRostersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/dashboard/$orgId': typeof AuthenticatedDashboardOrgIdRouteRouteWithChildren
  '/dashboard/rosters': typeof AuthenticatedDashboardRostersRouteRouteWithChildren
  '/dashboard/autograding': typeof AuthenticatedDashboardAutogradingRoute
  '/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$orgId/$classId': typeof AuthenticatedDashboardOrgIdClassIdRoute
  '/dashboard/rosters/$rosterId': typeof AuthenticatedDashboardRostersRosterIdRoute
  '/dashboard/$orgId/': typeof AuthenticatedDashboardOrgIdIndexRoute
  '/dashboard/rosters/': typeof AuthenticatedDashboardRostersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/autograding': typeof AuthenticatedDashboardAutogradingRoute
  '/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$orgId/$classId': typeof AuthenticatedDashboardOrgIdClassIdRoute
  '/dashboard/rosters/$rosterId': typeof AuthenticatedDashboardRostersRosterIdRoute
  '/dashboard/$orgId': typeof AuthenticatedDashboardOrgIdIndexRoute
  '/dashboard/rosters': typeof AuthenticatedDashboardRostersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/dashboard/$orgId': typeof AuthenticatedDashboardOrgIdRouteRouteWithChildren
  '/_authenticated/dashboard/rosters': typeof AuthenticatedDashboardRostersRouteRouteWithChildren
  '/_authenticated/dashboard/autograding': typeof AuthenticatedDashboardAutogradingRoute
  '/_authenticated/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/$orgId/$classId': typeof AuthenticatedDashboardOrgIdClassIdRoute
  '/_authenticated/dashboard/rosters/$rosterId': typeof AuthenticatedDashboardRostersRosterIdRoute
  '/_authenticated/dashboard/$orgId/': typeof AuthenticatedDashboardOrgIdIndexRoute
  '/_authenticated/dashboard/rosters/': typeof AuthenticatedDashboardRostersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/$orgId'
    | '/dashboard/rosters'
    | '/dashboard/autograding'
    | '/dashboard/organizations'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/$orgId/$classId'
    | '/dashboard/rosters/$rosterId'
    | '/dashboard/$orgId/'
    | '/dashboard/rosters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/autograding'
    | '/dashboard/organizations'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/$orgId/$classId'
    | '/dashboard/rosters/$rosterId'
    | '/dashboard/$orgId'
    | '/dashboard/rosters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/$orgId'
    | '/_authenticated/dashboard/rosters'
    | '/_authenticated/dashboard/autograding'
    | '/_authenticated/dashboard/organizations'
    | '/_authenticated/dashboard/settings'
    | '/api/auth/$'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/$orgId/$classId'
    | '/_authenticated/dashboard/rosters/$rosterId'
    | '/_authenticated/dashboard/$orgId/'
    | '/_authenticated/dashboard/rosters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/$orgId': {
      id: '/_authenticated/dashboard/$orgId'
      path: '/$orgId'
      fullPath: '/dashboard/$orgId'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/autograding': {
      id: '/_authenticated/dashboard/autograding'
      path: '/autograding'
      fullPath: '/dashboard/autograding'
      preLoaderRoute: typeof AuthenticatedDashboardAutogradingRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/organizations': {
      id: '/_authenticated/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/rosters': {
      id: '/_authenticated/dashboard/rosters'
      path: '/rosters'
      fullPath: '/dashboard/rosters'
      preLoaderRoute: typeof AuthenticatedDashboardRostersRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/$orgId/': {
      id: '/_authenticated/dashboard/$orgId/'
      path: '/'
      fullPath: '/dashboard/$orgId/'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRouteRoute
    }
    '/_authenticated/dashboard/$orgId/$classId': {
      id: '/_authenticated/dashboard/$orgId/$classId'
      path: '/$classId'
      fullPath: '/dashboard/$orgId/$classId'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdClassIdRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRouteRoute
    }
    '/_authenticated/dashboard/rosters/': {
      id: '/_authenticated/dashboard/rosters/'
      path: '/'
      fullPath: '/dashboard/rosters/'
      preLoaderRoute: typeof AuthenticatedDashboardRostersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRostersRouteRoute
    }
    '/_authenticated/dashboard/rosters/$rosterId': {
      id: '/_authenticated/dashboard/rosters/$rosterId'
      path: '/$rosterId'
      fullPath: '/dashboard/rosters/$rosterId'
      preLoaderRoute: typeof AuthenticatedDashboardRostersRosterIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRostersRouteRoute
    }
  }
}

interface AuthenticatedDashboardOrgIdRouteRouteChildren {
  AuthenticatedDashboardOrgIdClassIdRoute: typeof AuthenticatedDashboardOrgIdClassIdRoute
  AuthenticatedDashboardOrgIdIndexRoute: typeof AuthenticatedDashboardOrgIdIndexRoute
}

const AuthenticatedDashboardOrgIdRouteRouteChildren: AuthenticatedDashboardOrgIdRouteRouteChildren =
  {
    AuthenticatedDashboardOrgIdClassIdRoute:
      AuthenticatedDashboardOrgIdClassIdRoute,
    AuthenticatedDashboardOrgIdIndexRoute:
      AuthenticatedDashboardOrgIdIndexRoute,
  }

const AuthenticatedDashboardOrgIdRouteRouteWithChildren =
  AuthenticatedDashboardOrgIdRouteRoute._addFileChildren(
    AuthenticatedDashboardOrgIdRouteRouteChildren,
  )

interface AuthenticatedDashboardRostersRouteRouteChildren {
  AuthenticatedDashboardRostersRosterIdRoute: typeof AuthenticatedDashboardRostersRosterIdRoute
  AuthenticatedDashboardRostersIndexRoute: typeof AuthenticatedDashboardRostersIndexRoute
}

const AuthenticatedDashboardRostersRouteRouteChildren: AuthenticatedDashboardRostersRouteRouteChildren =
  {
    AuthenticatedDashboardRostersRosterIdRoute:
      AuthenticatedDashboardRostersRosterIdRoute,
    AuthenticatedDashboardRostersIndexRoute:
      AuthenticatedDashboardRostersIndexRoute,
  }

const AuthenticatedDashboardRostersRouteRouteWithChildren =
  AuthenticatedDashboardRostersRouteRoute._addFileChildren(
    AuthenticatedDashboardRostersRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardOrgIdRouteRoute: typeof AuthenticatedDashboardOrgIdRouteRouteWithChildren
  AuthenticatedDashboardRostersRouteRoute: typeof AuthenticatedDashboardRostersRouteRouteWithChildren
  AuthenticatedDashboardAutogradingRoute: typeof AuthenticatedDashboardAutogradingRoute
  AuthenticatedDashboardOrganizationsRoute: typeof AuthenticatedDashboardOrganizationsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardOrgIdRouteRoute:
      AuthenticatedDashboardOrgIdRouteRouteWithChildren,
    AuthenticatedDashboardRostersRouteRoute:
      AuthenticatedDashboardRostersRouteRouteWithChildren,
    AuthenticatedDashboardAutogradingRoute:
      AuthenticatedDashboardAutogradingRoute,
    AuthenticatedDashboardOrganizationsRoute:
      AuthenticatedDashboardOrganizationsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
